export const UI_LABELS = {
  app: {
    title: 'LDAPilot',
    description: 'Modern Samba4 Directory Services Management',
  },
  navigation: {
    adManagement: 'AD Management',
    dnsManager: 'DNS Manager',
    settings: 'Settings',
    dashboard: 'Dashboard',
  },
  ad: {
    title: 'Active Directory Management',
    users: 'Users',
    computers: 'Computers',
    groups: 'Groups',
    folders: 'Organizational Units',
    noSelection: 'Select an OU to view contents',
    addUser: 'Add User',
    addComputer: 'Add Computer',
    addGroup: 'Add Group',
  },
  dns: {
    title: 'DNS Records Manager',
    records: 'DNS Records',
    addRecord: 'Add Record',
    types: {
      A: 'A (IPv4)',
      AAAA: 'AAAA (IPv6)',
      CNAME: 'CNAME (Alias)',
      MX: 'MX (Mail)',
      NS: 'NS (Nameserver)',
      TXT: 'TXT (Text)',
      SOA: 'SOA (Start of Authority)',
      SRV: 'SRV (Service)',
      PTR: 'PTR (Reverse)',
    },
  },
  config: {
    title: 'LDAP Configuration',
    ldapServer: 'LDAP Server',
    hostname: 'Hostname',
    port: 'Port',
    protocol: 'Protocol', 
    domain: 'Domain',
    password: 'Password',
    testConnection: 'Test Connection',
    save: 'Save Configuration',
    profiles: 'Connection Profiles',
    newProfile: 'New Profile',
  },
  actions: {
    edit: 'Edit',
    view: 'View',
    delete: 'Delete',
    disable: 'Disable',
    enable: 'Enable',
    save: 'Save',
    cancel: 'Cancel',
    search: 'Search',
    filter: 'Filter',
    reset: 'Reset',
  },
  messages: {
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    confirming: 'Are you sure?',
    connectionFailed: 'Connection failed',
    connectionSuccess: 'Connection successful',
    saved: 'Saved successfully',
    deleted: 'Deleted successfully',
  },
} as const;
